language: ruby
bundler_args: --without development

gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/mm_rails4_2.gemfile
  - gemfiles/mm_rails5.gemfile

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.1.6.0

matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/mm_rails5.gemfile
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/rails5_0.gemfile
    - rvm: jruby-9.1.6.0
      gemfile: gemfiles/mm_rails5.gemfile

services:
  - mongodb

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
